# Buildpack API version
api = "0.4"
# api = "0.8"

# Buildpack ID and metadata
[buildpack]
id = "buildio/buildpack-dyno-metrics"
version = "0.0.2"
name = "Dyno Metrics Buildpack"
homepage = "https://github.com/buildio/buildpack-dyno-metrics/tree/main"

# Targets the buildpack will work with
[[targets]]
os = "linux"

# Stacks (deprecated) the buildpack will work with
[[stacks]]
id = "*"
